//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad.Web.Configuracion {
	
	
	public partial class MantenedorContratos {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden idactual;
		
		protected System.Web.UI.WebControls.TextBox txtRazonSocial;
		
		protected System.Web.UI.WebControls.TextBox txtRutEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtNombreFantasia;
		
		protected System.Web.UI.WebControls.TextBox txtDireccion;
		
		protected System.Web.UI.WebControls.TextBox txtComuna;
		
		protected System.Web.UI.WebControls.TextBox txtCiudad;
		
		protected System.Web.UI.WebControls.TextBox txtRegion;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoFijoEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoCelularEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtRepesentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoCelularRepresentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoFijoRepresentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtEmailRepresentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtCodigoActividad;
		
		protected System.Web.UI.WebControls.TextBox txtSitioWeb;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtRutUsuario;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtDuracionContrato;
		
		protected System.Web.UI.WebControls.TextBox txtFechaInicial;
		
		protected System.Web.UI.WebControls.TextBox txtFechaTermino;
		
		protected System.Web.UI.WebControls.TextBox txtCantidadTrabajadores;
		
		protected System.Web.UI.WebControls.TextBox txtCantidadUsuarios;
		
		protected System.Web.UI.WebControls.TextBox txtMensualidad;
		
		protected System.Web.UI.WebControls.DropDownList ddlEstado;
		
		protected System.Web.UI.WebControls.Button btnGuardarContrato;
		
		protected System.Web.UI.WebControls.Button btnVolver;
	}
}
