//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad.Web.Configuracion {
	
	
	public partial class MantenedorUsuarios {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroUsername;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroRut;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroNombre;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroApellido;
		
		protected System.Web.UI.WebControls.DropDownList ddlFiltroEstado;
		
		protected System.Web.UI.WebControls.Button btnBuscar;
		
		protected System.Web.UI.WebControls.Button btnLimpiar;
		
		protected System.Web.UI.WebControls.GridView gvTablaUsuarios;
		
		protected System.Web.UI.WebControls.Button btnEditarUsuario;
		
		protected System.Web.UI.WebControls.Button btnNuevoUsuario;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.TextBox txtIdUsuario;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtRut;
		
		protected System.Web.UI.WebControls.TextBox txtApellidoPaterno;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtFonoCelular;
		
		protected System.Web.UI.WebControls.TextBox txtUsername;
		
		protected System.Web.UI.WebControls.TextBox txtRepetirPassword;
		
		protected System.Web.UI.WebControls.TextBox txtNombres;
		
		protected System.Web.UI.WebControls.TextBox txtApellidoMaterno;
		
		protected System.Web.UI.WebControls.DropDownList ddlEstadoUsuario;
		
		protected System.Web.UI.WebControls.Button btnGuardarUsuario;
	}
}
