//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad.Web.Configuracion {
	
	
	public partial class MantenedorEmpresas {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroNombreEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroRutEmpresa;
		
		protected System.Web.UI.WebControls.DropDownList ddlFiltroEstadoEmpresa;
		
		protected System.Web.UI.WebControls.Button btnBuscarEmpresa;
		
		protected System.Web.UI.WebControls.Button btnLimpiarFiltroEmpresa;
		
		protected System.Web.UI.WebControls.GridView gvTablaEmpresa;
		
		protected System.Web.UI.WebControls.Button btnEditarEmpresa;
		
		protected System.Web.UI.WebControls.Button btnNuevaEmpresa;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.TextBox txtIdEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtRazonSocial;
		
		protected System.Web.UI.WebControls.TextBox txtDireccion;
		
		protected System.Web.UI.WebControls.TextBox txtComuna;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoFijoEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtEmailEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtRepesentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoCelularRepresentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtCodigoActividad;
		
		protected System.Web.UI.WebControls.DropDownList ddlEstadoEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtRutEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtNombreFantasia;
		
		protected System.Web.UI.WebControls.TextBox txtCiudad;
		
		protected System.Web.UI.WebControls.TextBox txtRegion;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoCelularEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtSitioWeb;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoFijoRepresentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtEmailRepresentanteLegal;
		
		protected System.Web.UI.WebControls.TextBox txtLogo;
		
		protected System.Web.UI.WebControls.Button btnGuardarEmpresa;
	}
}
