//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Web.Usuarios {
	
	
	public partial class ListarUsuarios {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroUsername;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroRut;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroNombre;
		
		protected System.Web.UI.WebControls.TextBox txtFiltroApellido;
		
		protected System.Web.UI.WebControls.Button btnLimpiar;
		
		protected System.Web.UI.WebControls.GridView gvTabla;
		
		protected System.Web.UI.WebControls.TextBox txtNombres;
		
		protected System.Web.UI.WebControls.TextBox txtApellidoPaterno;
		
		protected System.Web.UI.WebControls.TextBox txtApellidoMaterno;
		
		protected System.Web.UI.WebControls.TextBox txtRut;
		
		protected System.Web.UI.WebControls.DropDownList ddlSexo;
		
		protected System.Web.UI.WebControls.TextBox txtUsername;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoFijo;
		
		protected System.Web.UI.WebControls.TextBox txtTelefonoMovil;
		
		protected System.Web.UI.WebControls.TextBox txtDireccion;
		
		protected System.Web.UI.WebControls.Button btnGuardar;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoNombres;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoRut;
		
		protected System.Web.UI.WebControls.DropDownList ddlNuevoSexo;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoUsername;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoApellidos;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoFechaNacimiento;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoPerfil;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoEmail;
		
		protected System.Web.UI.WebControls.DropDownList ddlNuevoEstado;
	}
}
