//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.TextBox txtUsername;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.Label lblCredenInco;
		
		protected System.Web.UI.WebControls.Button btnIngresar;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoNombres;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoRut;
		
		protected System.Web.UI.WebControls.DropDownList ddlNuevoSexo;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoUsername;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoEmpresa;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoApellidos;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoFechaNacimiento;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoPerfil;
		
		protected System.Web.UI.WebControls.TextBox txtNuevoEmail;
		
		protected System.Web.UI.WebControls.DropDownList ddlNuevoEstado;
	}
}
